= Getting Started

== Introduction

To develop Yaktor based NodeJs applications, you'll have to install a few tools. We have an easy way to get started in which you simply need Docker, our Docker image will provide everthing else you will need to run an application. 

We strongly recommend that you use this approach. The https://github.com/SciSpike/yaktor#readme[Yaktor readme] is a great source for getting started using Docker.

However there may be reasons for running it outside of Docker. 
To do so the minimum requirements are https://nodejs.org/en/[Node.js] and https://www.mongodb.com[MongoDB]
In this document we're aiming at helping those that for whatever reason do not want to use Docker.

You are probably already familiar with Node.js development, and if you are, this is a simple +npm+ install.
In addition, we depend on a code generator which we from the command line or run in an IDE called Eclipse.

There are two distinct roles as well a link:#developer-role[Developer Role] and a link:#business-role[Business Role]

== Development Tools

* Eclipse
  ** Install the latest version of http://www.eclipse.org/downloads/[Eclipse]. If you prefer, you could instead install the latest version of Spring Tool Suite, Nodeeclipse, Enide, or any other IDE based on Eclipse.

  ** After installing Eclipse, you must install a few required plugins.
. In Eclipse, go to *Help > Install New Software*
+
For "Work with", select *--All Available Sites--* and install the _JavaScript Development Tools_ plugin.
+
. Next, add the following update site: http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
+
Select the update site you just added for "Work with" and install the _Xtext SDK_ plugin. Ensure that the version selected is at least 2.5. Otherwise you will run into conflicts in the next step.
+
. Finally, add another update site for the Yaktor plugins: http://yaktor.io/eclipse
+
Select the update site you just added for "Work with" and install both the _Conversation_ and _Domain_ plugins.

* Node.js
  .. Install the latest version of http://nodejs.org/download/[Node.js]
  .. If you already have Node.js installed, ensure that the version is >= v0.10
  .. +npm+ is a command line package manager for Node.js. It should have been automatically installed with the Node.js installation but you can use the following command to ensure it is installed.
  .. ensure you `export PATH=node_modules/.bin:$PATH`
+
[source,bash]
---------
npm help
---------
+
* MongoDB
  .. Install the latest version of http://docs.mongodb.org/manual/installation/[MongoDB]\

== Business Role

=== Getting a Conversation

In general if you are in the Business Role someone else would have created a project and it should be waiting in some source code repository for you to get.
For example it may be in github where you would:

[source,bash]
---------
git clone git@github.com:ORGNAME/PROJECT_NAME.git
---------

Now from the context of the cloned project:

[source,bash]
---------
npm install
---------

=== Install/Creating Conversation

In some instances you may be responsible for creating conversations. The process is simple. Here it is:

[source,bash]
---------
mkdir <someName> # <1>
cd <someName>
npm install yaktor@<version> # <2>
yaktor init # <3>
---------
<1> where `<someName>` is the name of the project you wish to create
<2> where `<version>` is a version name/number like `latest` or `2.0.0`
<3> you should run `yaktor init` every time you install a new version of yaktor


== Developer Role

This is not any regular developer, but rather someone who is contributing to the Yaktor projects (i.e. yaktor or yaktor-ui-angular1).

To build/test `yaktor` simply:
[source,bash]
---------
npm install <somePath> # <1>
yaktor init
---------
<1> where `<somepath>` is the actual path to your yaktor source code

=== Yaktor validation

All development and validation is done using Docker. Please see the https://github.com/SciSpike/yaktor[yaktor git repo].


== Import your project into Eclipse

After you have created the project using the +yaktor+ command line tool, you'll have to import this project into a workspace in Eclipse.
To do so, you must:

. Select *Import*
. Select *Existing projects into workspace*
. Browse to where you placed the new project
. Follow the remaining confirmation dialogs to add the project to your workspace

== Verify that the application runs
The application has a sample dsl file.
The example is simple and if everything is working, you should be all set.

Start essential services
. Mongo
If you followed the Mongo installation, you should have mongo on your path.You may have to run as sudo:

	mongod

== Develop your first conversation

For information about developing a conversation please read the link:../reference/languageReference.html[Conversation Language Reference].

== Trouble Shooting

=== .gitignore troubles

If you are receiving a +SyntaxError+ residing in a .gitignore file, Eclipse is not your friend. You must teach Eclipse
a lesson. Go to Preferences -> Team -> Git -> Project. Then *uncheck* "Automatically ignore derived resources by adding them to .gitignore".

[NOTE]
.Cleanup the mess
=====
[source, bash]
.In the root of your Project
---------
git ls-files --others --exclude-standard | grep .gitignore | xargs rm
---------
=====
