sudo: required

services:
  - docker

before_install:
  - env | grep TRAVIS > .env
  - docker pull yaktor/node:0.39.0

script:
  - docker run --rm -v $PWD:/app -w /app yaktor/node:0.39.0 bash -c ./build.rb
