= Yaktor Languages and Tools

== Introduction

Yaktor is a suite of tools and methods for producing highly scalable web applications.
Yaktor builds on top of existing technologies in order to produce the best applications possible.
However, it also has lots of features and benefits over using those existing technologies by themselves.

The documentation consists primarily of

* Reference Documentation
* Tutorials

The two most important things to learn are Yaktor's domain-specific languages (DSLs):

* The domain modeling DSL
* The conversation DSL

The domain modeling DSL is used to define a canonical information model for the problem domain the project is solving.

The conversation DSL is used to define the behavior of the application.

== I'm A Newbie. What Do I Do?

Here is a suggested learning path.

First, do a quick scan of the key reference documentation.
Even if you don't understand it all (yet), it should give you a good idea of what we are doing.

. link:conversation/tutorials/GettingStarted.html[Just About Everything]
. link:domain/reference/introduction.html[Learn the domain language]
. link:conversation/reference/languageReference.html[Learn the conversation language]

What to do next depends on your learning style.
For those of you that like to learn through experimentation, perhaps it's time to do a bit of exploration using some of the tutorials.
For those of you that like to start with a more theoretical foundation, perhaps a closer study of the reference documentation may be best.

== List of Documents

* Installation
** link:conversation/tutorials/GettingStarted.html[Getting Started]
* Domain Language
** References
*** link:domain/reference/introduction.html[Language reference]
*** link:domain/reference/node/mongo/gen-mongo-js.html[Generate Node and Mongoose]
*** link:domain/reference/java/roo/gen-roo.html[Generate Spring Roo]
** Tutorials
*** link:domain/tutorials/roo-tutorial.html[Spring Roo Tutorial]
** Platform Specific Documentation
*** link:domain/reference/node/mongo/gen-mongo-js.html[Generating Node.js and Mongo]
* Conversation Language
** References
*** link:conversation/reference/languageReference.html[Language reference]
*** link:conversation/reference/artifactsAndConcepts.html[Artifacts and Concepts]
*** link:conversation/reference/graphicalSyntaxReference.html[Graphical Syntax Reference]
*** link:conversation/reference/architecture/ConversationArchitecture.html[The conversation architecture]
** Tutorials (TBD)
